# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      runAgainst:
        type: choice
        description: Select Environment
        required: true
        options:
          - Test
          - Dev
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      RUN_AGAINST: ${{ github.event.inputs.runAgainst }} 
    steps:
          - uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v2
            with:
              java-version: '11'
              distribution: 'adopt'
              server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
              settings-path: ${{ github.workspace }} # location for the settings.xml file

          - name: Run Main
            run: javac ${{ github.workspace }}/src/Main.java && java ${{ github.workspace }}/Main
    
